# -*- coding: utf-8 -*-
"""CálculoDeSalário.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKoxfPTQUgunmueveoY3x-eERFSGcV8j
"""

from time import sleep
print('-=-'*40)
salario = float(input('Informe o salário do funcionário: R$ '))
print("CALCULANDO...")
sleep(2)
print('-=-'*40)
if salario <= 1250:
    novo = salario + (salario * 15 / 100)
else:
    novo = salario + (salario * 10 / 100)
print('Quem ganhava R$ \033[1;31m{:.2f}\033[m, passará a '
      'ganhar R$ \033[1;31m{:.2f}\033[m'.format(salario, novo))
print('-=-'*40)